#!/usr/bin/env python
# findlay@cosmic.utah.edu

import sys
from subprocess import Popen,PIPE
from argparse import ArgumentParser,FileType

files = '''\
/usr/local/bin/5kmlas_ctl
/etc/init.d/5kmlas_ctl
/etc/5kmlas_ctl/options
/etc/ppp/options
'''

def parse_args():
  arg_parser = ArgumentParser(description='send/receive files to/from 5 km laser SBC')
  arg_parser.add_argument('ip_addr',type=FileType('r'),help='file with IP address of SBC')
  transaction = arg_parser.add_mutually_exclusive_group(required=True)
  transaction.add_argument('-s','--send',action='store_true',help='send files [default]')
  transaction.add_argument('-r','--receive',action='store_true',help='receive files')
  try:
    parsed = arg_parser.parse_args()
    return parsed
  except IOError as io_error:
    print 'argument not a file: %s\n' % io_error
    print arg_parser.format_usage()
    sys.exit(1)

def main():
  args = parse_args()
  if args.send:
    rsync = Popen(('rsync','-av','--inplace','--files-from=-','.','root@%s:' % args.ip_addr.read().strip()),stdin=PIPE,stdout=PIPE,close_fds=True)
  elif args.receive:
    rsync = Popen(('rsync','-av','--files-from=-','root@%s:' % args.ip_addr.read().strip(),'.'),stdin=PIPE,stdout=PIPE,close_fds=True)
  rsync.stdin.write(files)
  print rsync.stdout.read()
  rsync.stdin.write(raw_input())
  print rsync.stdout.write()
  rsync.stdin.close() ; rsync.stdout.close()

if __name__ == '__main__' : main()
