#!/usr/bin/env python
# findlay@cosmic.utah.edu

import sys
from subprocess import Popen,PIPE
from argparse import ArgumentParser,FileType

files = '''\
/usr/local/bin/5kmlas_ctl
/etc/init.d/5kmlas_ctl
/etc/5kmlas_ctl/options
/etc/ppp/options
/etc/crontab
'''
ip_addr = '192.168.0.2'

def parse_args():
  arg_parser = ArgumentParser(description='send/receive files to/from 5 km laser SBC')
  transaction = arg_parser.add_mutually_exclusive_group(required=True)
  transaction.add_argument('-s','--send',action='store_true',help='send files [default]')
  transaction.add_argument('-r','--receive',action='store_true',help='receive files')
  return arg_parser.parse_args()

def main():
  args = parse_args()
  if args.send:
    rsync = Popen(('rsync','-av','--inplace','--files-from=-','.','root@%s:' % ip_addr),stdin=PIPE,stdout=PIPE,close_fds=True)
  elif args.receive:
    rsync = Popen(('rsync','-av','--files-from=-','root@%s:' % ip_addr,'.'),stdin=PIPE,stdout=PIPE,close_fds=True)
  rsync.stdin.write(files)
  print rsync.stdout.read()
  rsync.stdin.write(raw_input())
  print rsync.stdout.write()
  rsync.stdin.close() ; rsync.stdout.close()

if __name__ == '__main__' : main()
